language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.6"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "LoRa:0.5.0"
  - arduino --install-library "ArduinoJson:5.13.2"
script:
  # Arduino based examples
  - pushd examples/ARDUINO >/dev/null && build_platform mega2560 && popd >/dev/null
  - pushd examples/ESP8266 >/dev/null; build_platform esp32; popd >/dev/null
  # Linux examples
  - pushd examples/LINUX/Local/EthernetTCP/PingPong/Receiver/ >/dev/null; make; popd >/dev/null
notifications:
  email:
    on_success: change
    on_failure: change